### model
model_name_or_path: models/Qwen2.5-1.5b-Instruct          # policy

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_target: [q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj]
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05

### preference (DPO)
pref_loss: sigmoid
pref_beta: 0.1

### dataset
dataset: privacy_dpo_temperature_0.1_alpha_0.5_json
template: qwen
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 8

### output
output_dir: ./saved_models/qwen2.5_1.5b_dpo/temperature_0.1/alpha_0.5/beta_0.1/qwen2.5_1.5b_lora_dpo
logging_steps: 20
save_steps: 1000
plot_loss: true
overwrite_output_dir: true
save_total_limit: 2

### train
per_device_train_batch_size: 2 
gradient_accumulation_steps: 8
learning_rate: 5.0e-6
num_train_epochs: 7
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
gradient_checkpointing: true
ddp_timeout: 180000000

### eval
val_size: 0
eval_strategy: "no"


report_to: "none"

